"""remove_gs_anforderung_reference_field

Revision ID: 13be50ec3471
Revises: e47b89bcaa77
Create Date: 2023-02-19 10:50:37.285878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13be50ec3471"
down_revision = "e47b89bcaa77"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # copy data from gs_anforderung_reference to reference where reference is null
    op.execute(
        """
        UPDATE catalog_requirement
        SET reference = gs_anforderung_reference
        WHERE reference IS NULL
        """
    )

    # remove gs_anforderung_reference column from catalog_requirement table
    with op.batch_alter_table("catalog_requirement", schema=None) as batch_op:
        batch_op.drop_column("gs_anforderung_reference")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catalog_requirement", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("gs_anforderung_reference", sa.VARCHAR(), nullable=True)
        )

    # ### end Alembic commands ###
