"""name constraints

Revision ID: 4757e455dd37
Revises: ab13bba14886
Create Date: 2022-10-08 15:14:35.002390

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "4757e455dd37"
down_revision = "aaf70fa9151e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
