"""add common fields

Revision ID: 52864629f869
Revises: aaf70fa9151e
Create Date: 2022-10-04 20:06:54.945859

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '52864629f869'
down_revision = 'aaf70fa9151e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('document', sa.Column('updated', sa.DateTime(), nullable=False))
    op.add_column('gs_baustein', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('gs_baustein', sa.Column('updated', sa.DateTime(), nullable=False))
    op.add_column('measure', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('measure', sa.Column('updated', sa.DateTime(), nullable=False))
    op.add_column('project', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('project', sa.Column('updated', sa.DateTime(), nullable=False))
    op.add_column('requirement', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('requirement', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirement', 'updated')
    op.drop_column('requirement', 'created')
    op.drop_column('project', 'updated')
    op.drop_column('project', 'created')
    op.drop_column('measure', 'updated')
    op.drop_column('measure', 'created')
    op.drop_column('gs_baustein', 'updated')
    op.drop_column('gs_baustein', 'created')
    op.drop_column('document', 'updated')
    op.drop_column('document', 'created')
    # ### end Alembic commands ###
