"""add compliance fields to measure

Revision ID: 71cd375292ec
Revises: dea7e0cd1bf9
Create Date: 2023-01-07 09:31:32.614607

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '71cd375292ec'
down_revision = 'dea7e0cd1bf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compliance_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('compliance_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measure', schema=None) as batch_op:
        batch_op.drop_column('compliance_comment')
        batch_op.drop_column('compliance_status')

    # ### end Alembic commands ###
