"""add catalog

Revision ID: ab13bba14886
Revises: ad9f6e7bc41b
Create Date: 2022-10-07 21:40:28.491366

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision = "ab13bba14886"
down_revision = "ad9f6e7bc41b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("reference", AutoString(), nullable=True),
        sa.Column("title", AutoString(), nullable=False),
        sa.Column("description", AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("catalog_module", schema=None) as batch_op:
        batch_op.add_column(sa.Column("catalog_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "catalog", ["catalog_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catalog_module", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("catalog_id")

    op.drop_table("catalog")
    # ### end Alembic commands ###
