"""add catalog module

Revision ID: ad9f6e7bc41b
Revises: 52864629f869
Create Date: 2022-10-07 18:52:49.753172

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision = "ad9f6e7bc41b"
down_revision = "52864629f869"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_module",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("reference", AutoString(), nullable=True),
        sa.Column("title", AutoString(), nullable=False),
        sa.Column("description", AutoString(), nullable=True),
        sa.Column("gs_reference", AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("gs_baustein")
    with op.batch_alter_table("requirement", schema=None) as batch_op:
        batch_op.add_column(sa.Column("catalog_module_id", sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None, "catalog_module", ["catalog_module_id"], ["id"]
        )
        batch_op.drop_column("gs_baustein_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requirement", schema=None) as batch_op:
        batch_op.add_column(sa.Column("gs_baustein_id", sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "gs_baustein", ["gs_baustein_id"], ["id"])
        batch_op.drop_column("catalog_module_id")

    op.create_table(
        "gs_baustein",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("reference", sa.VARCHAR(), nullable=False),
        sa.Column("title", sa.VARCHAR(), nullable=False),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.Column("updated", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("catalog_module")
    # ### end Alembic commands ###
