"""remove gs reference field

Revision ID: bef7008ddd94
Revises: 13be50ec3471
Create Date: 2023-02-19 11:33:30.498334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bef7008ddd94"
down_revision = "13be50ec3471"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # copy data from gs_reference to reference where reference is null
    op.execute(
        """
        UPDATE catalog_module
        SET reference = gs_reference
        WHERE reference IS NULL
        """
    )

    # remove gs_reference column from catalog_module table
    with op.batch_alter_table("catalog_module", schema=None) as batch_op:
        batch_op.drop_column("gs_reference")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catalog_module", schema=None) as batch_op:
        batch_op.add_column(sa.Column("gs_reference", sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
