"""verification_validators

Revision ID: c083b27f9c47
Revises: bef7008ddd94
Create Date: 2023-03-04 12:10:07.859499

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "c083b27f9c47"
down_revision = "bef7008ddd94"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # set verification comment to null and verified to false
    # when verification method is not set
    op.execute(
        """
        UPDATE measure
        SET verification_method = 'R'
        WHERE verification_method IS NULL AND (
            verification_comment IS NOT NULL OR verified IS TRUE
        )
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
