"""add reference field to measure

Revision ID: dea7e0cd1bf9
Revises: 676ab3fb1339
Create Date: 2022-12-20 16:20:01.039469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dea7e0cd1bf9"
down_revision = "676ab3fb1339"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table("measure", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reference", sa.String(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("measure", schema=None) as batch_op:
        batch_op.drop_column("reference")

    # ### end Alembic commands ###
