"""add completion fields

Revision ID: e47b89bcaa77
Revises: 71cd375292ec
Create Date: 2023-01-08 13:59:45.711022

"""
from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision = "e47b89bcaa77"
down_revision = "71cd375292ec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table("measure", schema=None) as batch_op:
        batch_op.add_column(sa.Column("completion_status", AutoString(), nullable=True))
        batch_op.add_column(
            sa.Column("completion_comment", AutoString(), nullable=True)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("measure", schema=None) as batch_op:
        batch_op.drop_column("completion_comment")
        batch_op.drop_column("completion_status")

    # ### end Alembic commands ###
