"""rename field completed to verified

Revision ID: f94ba991ae4e
Revises: 4cd3702a9e46
Create Date: 2022-12-20 11:10:16.913789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f94ba991ae4e"
down_revision = "4cd3702a9e46"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # add column verified with nullable=True
    op.add_column("measure", sa.Column("verified", sa.Boolean(), nullable=True))

    # copy data from column completed to column verified
    op.execute("UPDATE measure SET verified = completed")

    # make column verified not nullable and drop column completed
    with op.batch_alter_table("measure", schema=None) as batch_op:
        batch_op.alter_column("verified", nullable=False)
        batch_op.drop_column("completed")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("measure", schema=None) as batch_op:
        batch_op.add_column(sa.Column("completed", sa.BOOLEAN(), nullable=False))
        batch_op.drop_column("verified")

    # ### end Alembic commands ###
