version: '3.8'
services:
  app:
    build:
      context: '..'
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    command: sleep infinity
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres:15.6
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: mvtool
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
