services:
  dev:
    build:
      context: '..'
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/mv-tool-api
    command: sleep infinity
    ports:
      - '8000:8000'
    depends_on:
      - ldap
      - db

  ldap:
    image: bitnami/openldap:2.5
    environment:
      LDAP_ADMIN_USERNAME: 'admin'
      LDAP_ADMIN_PASSWORD: 'adminpasswd'
      LDAP_USERS: 'user01,user02'
      LDAP_PASSWORDS: 'passwd01,passwd02'
      LDAP_ROOT: 'dc=example,dc=org'
      LDAP_ADMIN_DN: 'cn=admin,dc=example,dc=org'
    ports:
      - '1389:1389'
    volumes:
      - ldap_data:/bitnami/openldap

  db:
    image: postgres:15.6
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpasswd
      POSTGRES_DB: mvtool
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  ldap_data:
  postgres_data:
